### PR TITLE
basic operators added as well as some basic functions

### PR DESCRIPTION
**Pull request by Kramer84**
Hello, I have done some updates on your code.

Added some basic mathematical operators (normal and in place) for:
- summation
- subtraction
- division/ truedivision/ floor
- mod
- power

Added two basic functions to ndarray:
- tolist():
    to convert the ndarray into a comprehensive list
- argwhere()
   to return a list of keys, where the value of the ndarray match an other given value

Modified the __init__() method so it accepts also lists as a shape. 
Added the nan object (to be able to use np.nan).
Added the reshape function (not only as an method of the ndarray class)

The code is not entirely tested but should work.

I needed these functions in my project and had to work only with a basic python install using the standard library.

Thanks for the having made this project!

### CODE REVIEW

**Comment by wadetb** [comment]
Thanks for these changes, glad to hear the project was helpful.

**Comment by wadetb** [comment]
Can you restore the docs directory that was deleted, and also run `pytest` (may have to install it via pip) and ensure it succeeds?

**Comment by Kramer84** [comment]
The docs are restored and the _tinyndarray_ tests passed. The tests for the _tinynumpy_ script also pass, but only when _numpy_ is not installed, but I suppose this is expected behavior.

**Comment by wadetb** [comment]
Excellent, thank you!

**Pull request merged**
